version: '3'

services:
  iperf-server:
    image: networkstatic/iperf3
    container_name: "iperf3-s"
    hostname: "iperf-server"
    deploy: &hpc0
      placement:
        constraints:
           - "node.hostname==ocn0"
    ports:
      - "5201:5201/tcp"
    command: iperf3 -s
  
  iperf-client:
    image: networkstatic/iperf3
    container_name: "Iperf3-{{.Node.Hostname}}"
    hostname: "Iperf3-{{.Node.Hostname}}"
    deploy: &hpc0
      placement:
        constraints:
           - "node.hostname==ocn1"
    command: iperf3 -c iperf-server -J -P 4 -t 60